jwt:
  secret: project1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/first_project
    username: root
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: admin
      password: admin123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  web:
    resources:
      static-locations: classpath:/static/
